[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs ;

lib_deps = 
	esp32async/ESPAsyncWebServer@3.12.1
	ayushsharma82/ElegantOTA@4.0.0
	bblanchon/ArduinoJson@7.4.3

lib_compat_mode = strict
lib_ldf_mode = chain

; Ambiente per ESP32 Standard
[env:esp32dev]
board = esp32dev
board_build.partitions = partitions4MB.csv
build_flags =
	-I include 
	;-D WIFI_MGR_LOG ;WiFiManager Debug
	;-D SWITCHES_LOG=1 ;Switches Module Debug
	;-D SAFETY_LOG=1 ;SafetyMonitor Module Debug
	;-D DOME_LOG=1 ;Dome Module Debug
	;-D COVER_CALIBRATOR_LOG=1 ;CoverCalibrator Debug
	;-D BOARD_LOG=1 ;Board Module Debug
	;-D IOBASE_LOG=1 ;IOManagerLog
	-DASYNCWEBSERVER_LOG_CUSTOM=1
	-DCONFIG_ASYNC_TCP_LOG_CUSTOM=1
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

; Ambiente per ESP32-S3
[env:esp32-s3]
platform = espressif32 @ 6.10.0
board = esp32-s3-devkitc-1
build_flags = 
 	-I include
	;-D WIFI_MGR_LOG ;WiFiManager Debug
	;-D SWITCHES_LOG=1 ;Switches Module Debug
	;-D SAFETY_LOG=1 ;SafetyMonitor Module Debug
	;-D DOME_LOG=1 ;Dome Module Debug
	;-D COVER_CALIBRATOR_LOG=1 ;CoverCalibrator Debug
	;-D BOARD_LOG=1 ;Board Module Debug
	;-D IOBASE_LOG=1 ;IOManagerLog
	-D ASYNCWEBSERVER_LOG_CUSTOM=1
	-D CONFIG_ASYNC_TCP_LOG_CUSTOM=1
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D IS_ESP32S3=1
	-D CORE_DEBUG_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
